
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:5rc2
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: fix
        # https://github.com/actions/runner-images/issues/6775
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: check fmt of c code
        run: make checkfmt

      - name: check for SPDX tags
        run: ./tools/spdx-ensure

      - name: build
        run: ./build.sh
